site_name: 'Udemy Python'
site_description: 'Main documentation for udemy-python-app'
repo_url: https://github.com/ballakeita/udemy-python-app
edit_uri: edit/master/docs

plugins:
  - techdocs-core
  - redirects:
      redirect_maps:
        'index.md': 'overview/what-is-backstage.md'

# For sidebar navigation on https://backstage.io/, see `microsite/sidebars.js`
nav:
  - Overview:
      - Getting Started: 'docs/index.md'